### ISSUE TITLE
Add Native 3dst Support

### ISSUE THREAD

**Issue by Cracko298** [mc-3ds-team/GIMP-Grass-Colorizer-Script#1]
Script doesn't support 3dst support, only png or jpg images.

**Comment by ghost** [comment]
It's supposed to be a plugin for GIMP

**Comment by pizza-beep** [comment]
Cant plugins add file support?

**Comment by Cracko298** [comment]
> It's supposed to be a plugin for GIMP

I am genuinely asking why, this was brought up in a discord channel. And I was wondering why it doesn't have native 3dst support if it's meant for mc3ds.

It would be much more useful for it to natively support said texture format.

**Comment by SeveringHams** [comment]
It's important to note that this is written in a rather obscure programming language that has little to no documentation, and almost no use in the specific way I wanted to use it. So even examples of pixel-by-pixel manipulation were hard to come by. 

This is also an extremely basic programming language, based off of Scheme, a Lisp family language. It's extremely tedious, and gives little to no information on what went wrong during testing.

This script API is also entirely contained within GIMP. I cannot write a file interpreter, because it simply won't open the file. There is no raw byte reading at all. Script-Fu can do batch image edits, but Script-Fu interfaces only with GIMP, and GIMP interprets the files. But GIMP used to have Python-Fu, but seeing as it is no longer in the menu, I do not think it is supported anymore.

I chose this language, because GIMP is free, and none of the colorizer settings actually colorize the way Minecraft does.

It was _created_ to be used with MC3DS, but by no means was it intended _solely_ for MC3DS. Use it for whatever you want.

**Comment by Cracko298** [comment]
> It's important to note that this is written in a rather obscure programming language that has little to no documentation, and almost no use in the specific way I wanted to use it. So even examples of pixel-by-pixel manipulation were hard to come by. 
> 
> This is also an extremely basic programming language, based off of Scheme, a Lisp family language. It's extremely tedious, and gives little to no information on what went wrong during testing.
> 
> This script API is also entirely contained within GIMP. I cannot write a file interpreter, because it simply won't open the file. There is no raw byte reading at all. Script-Fu can do batch image edits, but Script-Fu interfaces only with GIMP, and GIMP interprets the files. But GIMP used to have Python-Fu, but seeing as it is no longer in the menu, I do not think it is supported anymore.
> 
> I chose this language, because GIMP is free, and none of the colorizer settings actually colorize the way Minecraft does.
> 
> It was _created_ to be used with MC3DS, but by no means was it intended _solely_ for MC3DS. Use it for whatever you want.

Thanks for the clarification!
